spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring_demo?useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=20000
    driverClassName: com.mysql.jdbc.Driver
    username: ${MYSQL_USERNAME:pcdbuser}
    password: ${MYSQL_PWD:pcdbuser}
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath*:/mybatis/*.xml # Tells mybatis to look in resources/mybatis for XML mappers
  type-aliases-package: com.azlan.test.model # Tells mybatis to look for our Client class in the right package

logging:
  level:
    org.springframework: DEBUG
    com.azlan.test: DEBUG
  pattern:
    console: "%date{yyyy-MM-dd'T'HH:mm:ss.SSSZ} %-5p [%logger] %msg MDC=[%X]%n%wex"

